### ISSUE TITLE
Bump ajv dep as part of upcoming breaking release

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/webkms-switch#16]
https://github.com/digitalbazaar/webkms-switch/pull/15

Not sure that there are any applicable breaking changes from v6 to v8

https://github.com/ajv-validator/ajv/releases/tag/v8.0.0
https://github.com/ajv-validator/ajv/releases/tag/v7.0.0

Also there is this guide: https://github.com/ajv-validator/ajv/blob/master/docs/v6-to-v8-migration.md

**Comment by dlongley** [comment]
Addressed by #18.
