### ISSUE TITLE
FIXME TODO count 2

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/webkms-switch#6]
- [ ] FIXME: it's possible that the operation terms have changed, the
       Commit: (e30f017) Include `kmsModule` in `key` and add FIXME.
       File:  [lib/index.js:117](https://github.com/digitalbazaar/webkms-switch/blob/master/lib/index.js#L117)
       Dave Longley commented a year ago

  - [ ] TODO: need to ensure `expectedTarget` matches `operation.invocationTarget`?
       Commit: (43127f1) Use http signature based zcap verification.
       File:  [lib/index.js:47](https://github.com/digitalbazaar/webkms-switch/blob/master/lib/index.js#L47)
       Dave Longley commented a year ago

**Comment by dlongley** [comment]
Addressed, closing.
